// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18052
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestSample.BrowserGuardEnabled
{
    using TechTalk.SpecFlow;
    using System.Configuration;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("BrowserRequiredTest")]
    [NUnit.Framework.CategoryAttribute("BrowserRequiredTestFeature")]
    [NUnit.Framework.CategoryAttribute("BrowserGuardEnabled")]
    public partial class BrowserRequiredTestFeature
    {
        
        private string Browser;
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BrowserRequiredTest", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
            this.Browser = null;
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            ScenarioContext.Current.Add("Browser", this.Browser);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
            testRunner.Given("I have a browser when running the background", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
        }
        
        private void GuardBrowserTagMissing()
        {
            var browserMissingMessage = ConfigurationManager.AppSettings["CatBrows-BrowserMissingMessage"] ?? "No browser defined, please specify @Browser:someBrowser for your scenario.";
            var enforceExistenceOfBrowserTagRaw = ConfigurationManager.AppSettings["CatBrows-RequiresBrowser"];
            bool enforceExistenceOfBrowserTag;
            bool hasConfigSetting = bool.TryParse(enforceExistenceOfBrowserTagRaw, out enforceExistenceOfBrowserTag);
            bool hasBrowser = !string.IsNullOrEmpty(this.Browser);
            bool shouldGuard = !(hasConfigSetting && !enforceExistenceOfBrowserTag);
            if (shouldGuard)
            {
                if (!hasBrowser)
                {
                    throw new System.Exception(browserMissingMessage);
                }
            }
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void NoTagsAtAll()
        {
            GuardBrowserTagMissing();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No tags at all", new string[] {
                        "ignore"});
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should throw a no browser exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.IgnoreAttribute()]
        [NUnit.Framework.CategoryAttribute("SomeTag")]
        public virtual void TagsButNoBrowserTag()
        {
            GuardBrowserTagMissing();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tags but no browser tag", new string[] {
                        "SomeTag",
                        "ignore"});
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should throw a no browser exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.TestCaseAttribute("chrome", Description="Single browser tag chrome (chrome)", Category="chrome")]
        public virtual void SingleBrowserTagChrome(string browser)
        {
            this.Browser = browser;
            GuardBrowserTagMissing();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single browser tag chrome", new string[] {
                        "Browser:chrome"});
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should have 1 testcase", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.TestCaseAttribute("firefox", Description="Multiple browser tags (firefox)", Category="firefox")]
        [NUnit.Framework.TestCaseAttribute("chrome", Description="Multiple browser tags (chrome)", Category="chrome")]
        public virtual void MultipleBrowserTags(string browser)
        {
            this.Browser = browser;
            GuardBrowserTagMissing();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple browser tags", new string[] {
                        "Browser:firefox",
                        "Browser:chrome"});
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should have 2 testcases", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.IgnoreAttribute()]
        [NUnit.Framework.TestCaseAttribute("value", null)]
        [NUnit.Framework.TestCaseAttribute("other value", null)]
        public virtual void NoTagsScenarioOutline(string header, string[] exampleTags)
        {
            GuardBrowserTagMissing();
            string[] @__tags = new string[] {
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No tags scenario outline", @__tags);
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should throw a no browser exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.IgnoreAttribute()]
        [NUnit.Framework.CategoryAttribute("sometag")]
        [NUnit.Framework.TestCaseAttribute("value", null)]
        [NUnit.Framework.TestCaseAttribute("other value", null)]
        public virtual void TagsButNoBrowserTagScenarioOutline(string header, string[] exampleTags)
        {
            GuardBrowserTagMissing();
            string[] @__tags = new string[] {
                    "sometag",
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tags but no browser tag scenario outline", @__tags);
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should throw a no browser exception", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.TestCaseAttribute("scenario-outline-browser", "value", null, Description="scenario outline with single browser tag (scenario-outline-browser)", Category="scenario-outline-browser")]
        public virtual void ScenarioOutlineWithSingleBrowserTag(string browser, string header, string[] exampleTags)
        {
            this.Browser = browser;
            GuardBrowserTagMissing();
            string[] @__tags = new string[] {
                    "Browser:scenario-outline-browser"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("scenario outline with single browser tag", @__tags);
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should have 1 testcases", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.TestCaseAttribute("chrome", "value", null, Description="scenario outline with two browser tags (chrome)", Category="chrome")]
        [NUnit.Framework.TestCaseAttribute("firefox", "value", null, Description="scenario outline with two browser tags (firefox)", Category="firefox")]
        public virtual void ScenarioOutlineWithTwoBrowserTags(string browser, string header, string[] exampleTags)
        {
            this.Browser = browser;
            GuardBrowserTagMissing();
            string[] @__tags = new string[] {
                    "Browser:chrome",
                    "Browser:firefox"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("scenario outline with two browser tags", @__tags);
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should have 2 testcases", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.CategoryAttribute("OutlineTag")]
        [NUnit.Framework.TestCaseAttribute("chrome", "nightly", new string[] {
                "nightly"}, Description="scenario outline with two browser tags and tagged examples (chrome)", Category="nightly,chrome")]
        [NUnit.Framework.TestCaseAttribute("firefox", "nightly", new string[] {
                "nightly"}, Description="scenario outline with two browser tags and tagged examples (firefox)", Category="nightly,firefox")]
        [NUnit.Framework.TestCaseAttribute("chrome", "each-commit", new string[] {
                "each-commit"}, Description="scenario outline with two browser tags and tagged examples (chrome)", Category="each-commit,chrome")]
        [NUnit.Framework.TestCaseAttribute("firefox", "each-commit", new string[] {
                "each-commit"}, Description="scenario outline with two browser tags and tagged examples (firefox)", Category="each-commit,firefox")]
        public virtual void ScenarioOutlineWithTwoBrowserTagsAndTaggedExamples(string browser, string header, string[] exampleTags)
        {
            this.Browser = browser;
            GuardBrowserTagMissing();
            string[] @__tags = new string[] {
                    "Browser:chrome",
                    "Browser:firefox",
                    "OutlineTag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("scenario outline with two browser tags and tagged examples", @__tags);
            this.ScenarioSetup(scenarioInfo);
            this.FeatureBackground();
            testRunner.Then("the test method should have 4 testcases", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
